In [1]:
import pandas as pd

In [2]:
student = {
    "Name":["Bhushan","Rahul","Sneha","Amit"],
    "Age":[22,21,23,24],
    "City":["Pune","Mumbai","Nashik","Delhi"],
    "Marks":[82,90,88,75]
}

df = pd.DataFrame(student)

df

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88
3     Amit   24   Delhi     75

In [3]:
df.head()

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88
3     Amit   24   Delhi     75

In [4]:
df.tail()

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88
3     Amit   24   Delhi     75

In [5]:
df.shape

(4, 4)

In [6]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='str')

In [7]:
df.dtypes

Name       str
Age      int64
City       str
Marks    int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
 3   Marks   4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [9]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   22.500000  83.750000
std     1.290994   6.751543
min    21.000000  75.000000
25%    21.750000  80.250000
50%    22.500000  85.000000
75%    23.250000  88.500000
max    24.000000  90.000000