In [21]:
import pandas as pd

In [22]:
student = {
    "Name":["Bhushan","Rahul","Sneha","Amit"],
    "Age":[22,21,23,24],
    "City":["Pune","Mumbai","Nashik","Delhi"],
    "Marks":[82,90,88,75]
}

df = pd.DataFrame(student)

df

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88
3     Amit   24   Delhi     75

In [23]:
df["Name"]

0    Bhushan
1      Rahul
2      Sneha
3       Amit
Name: Name, dtype: str

In [24]:
df[["Name"]]

      Name
0  Bhushan
1    Rahul
2    Sneha
3     Amit

In [25]:
df['Age']

0    22
1    21
2    23
3    24
Name: Age, dtype: int64

In [26]:
df[["Name","Marks"]]

      Name  Marks
0  Bhushan     82
1    Rahul     90
2    Sneha     88
3     Amit     75

In [27]:
df.loc[0]

Name     Bhushan
Age           22
City        Pune
Marks         82
Name: 0, dtype: object

In [28]:
df.iloc[0]

Name     Bhushan
Age           22
City        Pune
Marks         82
Name: 0, dtype: object

In [29]:
df.iloc[0:3]

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88

In [30]:
type(df["Age"])

pandas.Series

In [31]:
type(df[["Age"]])

pandas.DataFrame