In [12]:
import pandas as pd

In [13]:
student = {
    "Name":["Bhushan","Rahul","Sneha","Amit","Karan"],
    "Age":[22,21,23,24,22],
    "City":["Pune","Mumbai","Nashik","Delhi","Pune"],
    "Marks":[82,90,88,75,95]
}

df = pd.DataFrame(student)

df

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88
3     Amit   24   Delhi     75
4    Karan   22    Pune     95

In [14]:
df[df["Marks"] > 80]  # does not modify the original dataframe, it returns a new dataframe with only those rows where Marks > 80

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88
4    Karan   22    Pune     95

In [15]:
df

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
2    Sneha   23  Nashik     88
3     Amit   24   Delhi     75
4    Karan   22    Pune     95

In [16]:
df[df["City"] == "Pune"]

      Name  Age  City  Marks
0  Bhushan   22  Pune     82
4    Karan   22  Pune     95

In [17]:
df[df["Age"] < 23]

      Name  Age    City  Marks
0  Bhushan   22    Pune     82
1    Rahul   21  Mumbai     90
4    Karan   22    Pune     95

In [18]:
df[(df["Marks"] > 80) & (df["City"] == "Pune")]

      Name  Age  City  Marks
0  Bhushan   22  Pune     82
4    Karan   22  Pune     95

In [19]:
df[(df["Marks"] > 90) | (df["City"] == "Mumbai")]

    Name  Age    City  Marks
1  Rahul   21  Mumbai     90
4  Karan   22    Pune     95

In [20]:
len(df[df["Marks"] > 80])

4

In [24]:
# 🎯 Mini Challenge

# Using the same DataFrame:

# Students with marks ≥ 85.
# Students from Mumbai.
# Students aged 22.
# Students from Pune with marks > 90.
# Students from Delhi OR age > 22.

In [25]:
df[df["Marks"] >= 85]

    Name  Age    City  Marks
1  Rahul   21  Mumbai     90
2  Sneha   23  Nashik     88
4  Karan   22    Pune     95

In [26]:
df[df["City"] == "Mumbai"]

    Name  Age    City  Marks
1  Rahul   21  Mumbai     90

In [27]:
df[df["Age"] == 22]

      Name  Age  City  Marks
0  Bhushan   22  Pune     82
4    Karan   22  Pune     95

In [28]:
df[(df["City"] == "Pune") & (df["Marks"] > 90)]

    Name  Age  City  Marks
4  Karan   22  Pune     95

In [31]:
df[(df["City"] == "Delhi") | (df["Age"] > 22)]

    Name  Age    City  Marks
2  Sneha   23  Nashik     88
3   Amit   24   Delhi     75